export const UPDATE_DASHBOARD_DATA = 'UPDATE_DASHBOARD_DATA';
export const GET_PROPERTY_DATA_API = 'GET_PROPERTY_DATA_API';
export const UPDATE_SELECTED_TILE = 'UPDATE_SELECTED_TILE';
export const UPDATE_CURRENT_ROUTE = 'UPDATE_CURRENT_ROUTE';

//spinner
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';